cardapio = [
    {'number': 1, 'prato': 'Escondidinho de batata doce com carne de patinho','tipo':'funcional'},
    {'number': 2, 'prato': 'Escondidionho de batata doce com frango desfiado','tipo':'funcional'},
    {'number': 3, 'prato': 'Nhoque de batata doce, acompanha carne de patinho ao molho caseiro','tipo':'funcional'},
    {'number': 4, 'prato': 'Estrogonofe de frango com arroz integral e mix de legumes','tipo':'funcional'},
    {'number': 5, 'prato': 'Estrogonofe de carne de patinho com arroz integral e mix de legumes','tipo':'funcional'},
    {'number': 6, 'prato': 'Frango na mostarda, purê de batata doce e mix de legumes','tipo':'funcional'},
    {'number': 7, 'prato': 'Lombinho suíno, mandioca saute e repolho roxo','tipo':'funcional'},
    {'number': 8, 'prato': 'Carne de panela ao molho, mandioca e mix de legumes','tipo':'funcional'},
    {'number': 9, 'prato': 'Macarronada fit','tipo':'funcional'},
    {'number': 10, 'prato': 'Risoto de Frango','tipo':'funcional'},
    {'number': 11, 'prato': 'Yakissoba','tipo':'funcional'},
    {'number': 12, 'prato': 'Arroz integral, feijão, frango grelhado e mix de legumes','tipo':'funcional'},
    {'number': 13, 'prato': 'Frango cremoso com espaguete integral e mix de legumes','tipo':'funcional'},
    {'number': 14, 'prato': 'Escondidinho de aipim com carne de patinho','tipo':'funcional'},
    {'number': 15, 'prato': 'Escondidinho de aimpim com frango','tipo':'funcional'},
    {'number': 16, 'prato': 'Escondidinho de abóbora com frango desfiado e linguiça blumenau','tipo':'funcional'},
    {'number': 17, 'prato': 'Filé de frango ao molho de tangerina, acompaha arroz à grega','tipo':'funcional'},
    {'number': 18, 'prato': 'Almôndegas de carne ao molho de tomate, acompanha purê de mandioquinha','tipo':'funcional'},
    {'number': 19, 'prato': 'Ragu de carne com purê de abóbora cabotia e mix de legumes','tipo':'funcional'},
    {'number': 20, 'prato': 'Grelhadinho oriental com purê de batata salsa','tipo':'funcional'},
    {'number': 21, 'prato': 'Estrogonofe de carne, batata salsa e espaguete de cenoura','tipo':'funcional'},
    {'number': 22, 'prato': 'Escondiddinho de couve flor com carne desfiada e linguiça blumenau','tipo':'low carb'},
    {'number': 23, 'prato': 'Salteados de legumes com carne','tipo':'low carb'},
    {'number': 24, 'prato': 'Estrogonofe de frago com arroz de brócolis e bacon','tipo':'low carb'},
    {'number': 25, 'prato': 'Lasanha de carne low','tipo':'low carb'},
    {'number': 26, 'prato': 'Frango ao curry low carb','tipo':'low carb'},
    {'number': 27, 'prato': 'Escondidinho de couve flor com frango','tipo':'low carb'},
    {'number': 28, 'prato': 'Espaguete de legumes com frango ao molho sugo','tipo':'low carb'},
    {'number': 29, 'prato': 'Panqueca de frango low carb, acompanha molho de tomate caseiro e queijo','tipo':'low carb'},
    {'number': 30, 'prato': 'Lasanha de frango low','tipo':'low carb'},
    {'number': 31, 'prato': 'Panqueca de carne lowcarb, acompanha molho de tomate caseiro e queijo','tipo':'low carb'},
    {'number': 32, 'prato': 'Talharim de espinafre ao molho de tomate cereja e manjericão','tipo':'vegano'},
    {'number': 33, 'prato': 'Espaguete de abobrinha com azeitona ao molho sugo','tipo':'vegano'},
    {'number': 34, 'prato': 'Nhoque de batata doce com salsinha','tipo':'vegano'},
    {'number': 35, 'prato': 'Mix de vegetais com especiarias','tipo':'vegano'},
    {'number': 36, 'prato': 'Risoto de quinoa com palmito e azeitonas','tipo':'vegano'},
    {'number': 37, 'prato': 'Abobrinha gratinada','tipo':'vegano'},
    {'number': 38, 'prato': 'Purê de mandioquinha com vegetais ao vapor','tipo':'vegano'},
]

