funcional = [
    {'number': 1, 'prato': 'Escondidinho de batata doce com carne de patinho'},
    {'number': 2, 'prato': 'Escondidionho de batata doce com frango desfiado'},
    {'number': 3, 'prato': 'Nhoque de batata doce, acompanha carne de patinho ao molho caseiro'},
    {'number': 4, 'prato': 'Estrogonofe de frango com arroz integral e mix de legumes'},
    {'number': 5, 'prato': 'Estrogonofe de carne de patinho com arroz integral e mix de legumes'},
    {'number': 6, 'prato': 'Frango na mostarda, purê de batata doce e mix de legumes'},
    {'number': 7, 'prato': 'Lombinho suíno, mandioca saute e repolho roxo'},
    {'number': 8, 'prato': 'Carn de panela ao molho, mandioca e mix de legumes'},
    {'number': 9, 'prato': 'Macarronada fit'},
    {'number': 10, 'prato': 'Risoto de Frango'},
    {'number': 11, 'prato': 'Yakissoba'},
    {'number': 12, 'prato': 'Arroz integral, feijão, frango grelhado e mix de legumes'},
    {'number': 13, 'prato': 'Frango cremoso com espaguete integral e mix de legumes'},
    {'number': 14, 'prato': 'Escondidinho de aipim com carne de patinho'},
    {'number': 15, 'prato': 'Escondidinho de aimpim com frango'},
    {'number': 16, 'prato': 'Escondidinho de abóbora com frango desfiado e linguiça blumenau'},
    {'number': 17, 'prato': 'Filé de frango ao molho de tangerina, acompaha arroz à grega'},
    {'number': 18, 'prato': 'Almôndegas de carne ao molho de tomate, acompanha purê de mandioquinha'},
    {'number': 19, 'prato': 'Ragu de carne com purê de abóbora cabotia e mix de legumes'},
    {'number': 20, 'prato': 'Grelhadinho oriental com purê de batata salsa'},
    {'number': 21, 'prato': 'Estrogonofe de carne, batata salsa e espaguete de cenoura'},
]
